### ISSUE TITLE
GLSL Compilation Errors

### ISSUE THREAD

**Issue by biller23** [iryoku/smaa#4]
I tried to compile the last SMAA.hlsl with the following:
# define SMAA_GLSL_3   1
# define SMAA_PRESET_MEDIUM     1
# define SMAA_PREDICATION 1

My (Nvidia Geforce GT430) GLSL compiler complains:

0(614) : error C7011: implicit cast from "float" to "bool"
0(615) : error C7011: implicit cast from "float" to "bool"
0(1269) : error C1115: unable to find compatible overloaded function "SMAAMovc(bool, vec4, vec4)"
0(1270) : error C1115: unable to find compatible overloaded function "SMAAMovc(bool, vec2, vec2)"
0(1271) : error C7011: implicit cast from "float" to "vec2"

EDIT: corrected line number, basically are simple cast errors

these error are easily fixable:
    614 : SMAA_FLATTEN if (bool(cond.x)) variable.x = value.x;
    615 : SMAA_FLATTEN if (bool(cond.y)) variable.y = value.y;
    1269: SMAAMovc(vec4(horizontal), blendingOffset, float4(a.x, 0.0, a.z, 0.0));
    1270: SMAAMovc(vec2(horizontal), blendingWeight, a.xz);
    1271: blendingWeight /= dot(blendingWeight, vec2(1.0));

EDIT2: there are many more cast errors if compiled in ULTRA or HIGH (const float to vec2), but once fixed i get a very strange link error:

(0) : fatal error C9999: **\* exception during compilation ***

This error popup only in ULTRA or HIGH mode, I don't know I can possibly fix this.

**Comment by iryoku** [comment]
I checked compilation in RenderMonkey using GLSL and I think I've fixed all the compilation problems for MEDIUM, ULTRA and HIGH, but please confirm me if latest version works for you.

For what I've gathered, the link problem seems to be a driver problem; in RenderMoneky it links fine for me. Can you please update to latest version? And can you also tell me which GPU and driver version are you using?

Also, for checking the source of the fatal error, can you please turn features one by one instead of using a preset? You can check how the presets are being used, and check the differences between MEDIUM and HIGH, to find out which one is triggering the problem:

#elif SMAA_PRESET_MEDIUM
#define SMAA_THRESHOLD 0.1
#define SMAA_MAX_SEARCH_STEPS 8
#define SMAA_MAX_SEARCH_STEPS_DIAG 0
#define SMAA_CORNER_ROUNDING 100
#elif SMAA_PRESET_HIGH
#define SMAA_THRESHOLD 0.1
#define SMAA_MAX_SEARCH_STEPS 16
#define SMAA_MAX_SEARCH_STEPS_DIAG 8
#define SMAA_CORNER_ROUNDING 25

Thanks!

**Comment by iryoku** [comment]
I edited previous message, I'm writing this just to ensure you get a notification mail accordingly.

**Comment by biller23** [comment]
My video card is a Nvidia GeForce GT430 driver up to date (327.23) that support OpenGL up to 4.3/4.4.

I used successfully version 2.7 and the recent official download 2.8 (I always done only one minor modification to SMAASearchLength() adding "e.g = -e.g;" before the return statement for OpenGL). No problem compiling or linking whatsoever, no matter the preset I choose.

The problems occurs with the latest.

The latest version still has some minor compilation error easy fixable:

error C7011: implicit cast from "float" to "bool"
error C7011: implicit cast from "float" to "bool"
error C7505: OpenGL does not allow swizzles on scalar expressions
error C7505: OpenGL does not allow swizzles on scalar expressions

I simply make these changes:
    SMAA_FLATTEN if (bool(cond.x)) variable.x = value.x;
    SMAA_FLATTEN if (bool(cond.y)) variable.y = value.y;
and:
    SMAAMovc(float4(horizontal), blendingOffset, float4(a.x, 0.0, a.z, 0.0));
    SMAAMovc(float2(horizontal), blendingWeight, a.xz);

When fixed, there are no more compilation errror.

I discovered that the issue arises when I set SMAA_MAX_SEARCH_STEPS_DIAG to ANY VALUE different then 0. The compilation passes BUT the linking process returns the error that I previously reported and only this error (this is why with preset LOW or MEDIUM it is all fine).
The validation process fails and it simply returns this message:

(0) : fatal error C9999: **\* exception during compilation ***

**Comment by iryoku** [comment]
I tested on my Intel and NVIDIA GPUs, and found these errors as well (they didn't happened on my AMD desktop). I fixed them in latest commit (in a slightly different way to what you proposed, as it was not working for HLSL).

However, I was not able to replicate the link error in any of my machines (AMD Radeon 7970, NVIDIA GT 540M and Intel HD Graphics 3000) using RenderMonkey. It could be very useful for me if you can test out this little Render Monkey project on it, and see if it compiles properly:
www.iryoku.com/SMAA.rfx

Thanks!

**Comment by biller23** [comment]
Thank you very much for your help. There was no link error compiling the .rfx in RenderMonkey.

When I compiled the last SMAA.hlsl in my program, the linking error was present EVEN if   SMAA_MAX_SEARCH_STEPS_DIAG was 0 and I was surprised.

But then I finally found out the origin of the issue. As you said, It's probably a driver bug and it arises if I define SMAA_RT_METRICS  as an uniform vector instead of hard coding it. But only happens with the last versions of SMAA.

It was this line that opened my mind in your RenderMonkey file:
<code> #define SMAA_RT_METRICS float4(1.0 / 1280.0, 1.0 / 720.0, 1280.0, 720.0) </code>

I was using this definition:

<code> layout(std140)  uniform ImageSettings {
    vec4 size_inv;  // w, h, 1/w, 1/h
} image;
#define SMAA_RT_METRICS     image.size_inv.zwxy </code>

Then I changed with a simple uniform out of the uniform block:
<code>uniform vec4 scr_size; 
#define SMAA_RT_METRICS     scr_size</code>
but the result is the same: the linking process fails...

So the only way to compile successfully the last versions of SMAA in my computer and my drivers it seems to me hard coding the SMAA_RT_METRICS definition...

As a side note, I want to add that many cast error are still present if GLSL4 is used (float to float2 in mad() over the code).

Sorry for my english and thanks for your help !

**Comment by iryoku** [comment]
I've fixed GLSL 4 compilation bugs, and found out that defining the size as uniform was giving a linker error on my NVIDIA laptop as well (in the RenderMonkey project).

I rearranged the diagonal code a little bit, and seems to be working (just move the float3(...) outside of the loop), can you test latest version?

Thanks!

**Comment by biller23** [comment]
The latest version works fine. The issue is finally gone.
Thank you very much!
